# Generated by Django 3.1.2 on 2021-05-18 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='source_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_operations', to='manager.currency'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='target_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_operations', to='manager.currency'),
        ),
    ]
