# Generated by Django 3.1.2 on 2021-05-19 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20210518_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='fee',
            new_name='fee_amount',
        ),
    ]
