# Generated by Django 3.1.2 on 2021-05-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20210519_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
