# Generated by Django 3.1.2 on 2021-05-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_operation_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='converted_amount',
            field=models.DecimalField(decimal_places=8, max_digits=21),
        ),
        migrations.AlterField(
            model_name='operation',
            name='fee_amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='operation',
            name='source_amount',
            field=models.DecimalField(decimal_places=8, max_digits=21),
        ),
        migrations.AlterField(
            model_name='operation',
            name='total',
            field=models.DecimalField(decimal_places=8, max_digits=21),
        ),
    ]
